FROM masnagam/mirakc:${TARGETARCH}${TARGETVARIANT} AS image

FROM debian:buster-slim
LABEL maintainer="Masayuki Nagamachi <masnagam@gmail.com>"

COPY --from=image /usr/local/bin/* /usr/local/bin/

ENV MIRAKC_CONFIG=/etc/mirakc/config.yml
EXPOSE 40772
VOLUME ["/var/lib/mirakc/epg"]
ENTRYPOINT ["mirakc"]
CMD []
